"""initial schema

Revision ID: 9ed0bb020589
Revises: 
Create Date: 2026-06-15 19:37:08.323482
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9ed0bb020589'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('role', sa.Enum('user', 'admin', name='user_role'), nullable=False),
    sa.Column('approval_status', sa.Enum('pending', 'approved', 'rejected', name='approval_status'), nullable=False),
    sa.Column('oauth_provider', sa.String(length=40), nullable=True),
    sa.Column('oauth_subject', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_oauth_subject'), 'users', ['oauth_subject'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    op.create_table('collections',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('type', sa.Enum('user', 'album', 'tag', 'shared', name='collection_type'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_collections_owner_id'), 'collections', ['owner_id'], unique=False)
    op.create_table('libraries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('last_scan', sa.DateTime(timezone=True), nullable=True),
    sa.Column('track_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_libraries_owner_id'), 'libraries', ['owner_id'], unique=False)
    op.create_table('tracks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('artist', sa.String(length=512), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('normalized_artist', sa.String(length=512), nullable=False),
    sa.Column('normalized_title', sa.String(length=512), nullable=False),
    sa.Column('merged_keys', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('manual', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tracks_normalized_artist'), 'tracks', ['normalized_artist'], unique=False)
    op.create_index(op.f('ix_tracks_normalized_title'), 'tracks', ['normalized_title'], unique=False)
    op.create_index(op.f('ix_tracks_owner_id'), 'tracks', ['owner_id'], unique=False)
    op.create_table('collection_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('collection_id', 'track_id', name='uq_collection_track')
    )
    op.create_index(op.f('ix_collection_items_collection_id'), 'collection_items', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_items_track_id'), 'collection_items', ['track_id'], unique=False)
    op.create_table('shares',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('collection_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('shared_with_user_id', sa.Integer(), nullable=True),
    sa.Column('permission', sa.Enum('view', name='share_permission'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shared_with_user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shares_collection_id'), 'shares', ['collection_id'], unique=False)
    op.create_index(op.f('ix_shares_owner_id'), 'shares', ['owner_id'], unique=False)
    op.create_index(op.f('ix_shares_shared_with_user_id'), 'shares', ['shared_with_user_id'], unique=False)
    op.create_index(op.f('ix_shares_token'), 'shares', ['token'], unique=True)
    op.create_table('streaming_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('service', sa.Enum('spotify', 'tidal', 'qobuz', 'deezer', 'amazon_music', 'youtube_music', name='streaming_service'), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('track_id', 'service', name='uq_streaming_track_service')
    )
    op.create_index(op.f('ix_streaming_links_track_id'), 'streaming_links', ['track_id'], unique=False)
    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('library_id', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('codec', sa.String(length=40), nullable=True),
    sa.Column('container', sa.String(length=40), nullable=True),
    sa.Column('bitrate', sa.Integer(), nullable=True),
    sa.Column('bit_depth', sa.Integer(), nullable=True),
    sa.Column('sample_rate', sa.Integer(), nullable=True),
    sa.Column('channels', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Float(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('album', sa.String(length=512), nullable=True),
    sa.Column('year', sa.Integer(), nullable=True),
    sa.Column('genre', sa.String(length=160), nullable=True),
    sa.Column('track_number', sa.Integer(), nullable=True),
    sa.Column('disc_number', sa.Integer(), nullable=True),
    sa.Column('composer', sa.String(length=512), nullable=True),
    sa.Column('publisher', sa.String(length=255), nullable=True),
    sa.Column('replay_gain', sa.String(length=80), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('raw_metadata', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('pinned', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['library_id'], ['libraries.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('library_id', 'file_path', name='uq_variant_library_path')
    )
    op.create_index(op.f('ix_variants_library_id'), 'variants', ['library_id'], unique=False)
    op.create_index(op.f('ix_variants_track_id'), 'variants', ['track_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_variants_track_id'), table_name='variants')
    op.drop_index(op.f('ix_variants_library_id'), table_name='variants')
    op.drop_table('variants')
    op.drop_index(op.f('ix_streaming_links_track_id'), table_name='streaming_links')
    op.drop_table('streaming_links')
    op.drop_index(op.f('ix_shares_token'), table_name='shares')
    op.drop_index(op.f('ix_shares_shared_with_user_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_owner_id'), table_name='shares')
    op.drop_index(op.f('ix_shares_collection_id'), table_name='shares')
    op.drop_table('shares')
    op.drop_index(op.f('ix_collection_items_track_id'), table_name='collection_items')
    op.drop_index(op.f('ix_collection_items_collection_id'), table_name='collection_items')
    op.drop_table('collection_items')
    op.drop_index(op.f('ix_tracks_owner_id'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_normalized_title'), table_name='tracks')
    op.drop_index(op.f('ix_tracks_normalized_artist'), table_name='tracks')
    op.drop_table('tracks')
    op.drop_index(op.f('ix_libraries_owner_id'), table_name='libraries')
    op.drop_table('libraries')
    op.drop_index(op.f('ix_collections_owner_id'), table_name='collections')
    op.drop_table('collections')
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_oauth_subject'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # Drop the ENUM types created implicitly with the tables above.
    for enum_name in (
        'user_role',
        'approval_status',
        'collection_type',
        'streaming_service',
        'share_permission',
    ):
        sa.Enum(name=enum_name).drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
